name: Test Android Devices [gpu1]

on:
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run tests against"
        type: choice
        options:
          - prod
          - dev
        default: "prod"
        required: true

jobs:
  test-android-devices:
    name: ${{ matrix.device }} - API ${{ matrix.api-level }}${{ matrix.google-play && ' Play' || '' }}
    runs-on: ubuntu-latest

    strategy:
      # Don't cancel all jobs if one fails
      fail-fast: false
      matrix:
        include:
          # gpu1 only supports Pixel 7 with API 34-35
          - device: pixel-7
            api-level: "34"
          - device: pixel-7
            api-level: "35"

          # Google Play versions of Pixel 7
          - device: pixel-7
            api-level: "34"
            google-play: true
          - device: pixel-7
            api-level: "35"
            google-play: true


    steps:
      - uses: actions/checkout@v3

      - name: Run Android Device Tests
        uses: devicecloud-dev/device-cloud-for-maestro@v2
        with:
          api-key: ${{ github.event.inputs.environment == 'dev' && secrets.DCD_DEV_API_KEY || secrets.DCD_API_KEY }}
          api-url: ${{ github.event.inputs.environment == 'dev' && 'https://api.dev.devicecloud.dev' || '' }}
          app-file: ./binaries/sample.apk
          workspace: ./flows/android-flow.yaml
          android-device: ${{ matrix.device }}
          android-api-level: ${{ matrix.api-level }}
          google-play: ${{ matrix.google-play || '' }}
          runner-type: gpu1
          name: "${{ matrix.device }} - Android API ${{ matrix.api-level }}${{ matrix.google-play && ' with Play' || '' }} Test Run"
